export const layout: string;
export const head: string;
export const headIcon: string;
export const headTitle: string;
export const headTitleMain: string;
export const headTitleAdd: string;
export const headParams: string;
export const actions: string;
export const description: string;
